spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/c_bomb?autoReconnect=true
    username: root
    password: xoghks1004
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: ture
        format_sql: true
    open-in-view: false
